packages:
  - packages/app/*
  - packages/features/top/*
  - packages/features/note/*
  - packages/features/user/*
  - packages/features/shared/*
  - packages/shared/*
  - packages/di
catalog:
  '@eslint/js': ^9.21.0
  '@tsconfig/node22': ^22.0.0
  '@types/jsdom': ^21.1.7
  '@types/json-schema': ^7.0.15
  '@types/node': ^22.13.4
  '@typescript-eslint/eslint-plugin': ^8.24.1
  '@typescript-eslint/parser': ^8.24.1
  '@vitejs/plugin-vue': ^5.2.1
  '@vue/eslint-config-typescript': ^14.4.0
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  eslint: ^9.21.0
  eslint-plugin-vue: ^9.32.0
  inversify: ^6.0.1
  jiti: ^2.4.2
  jsdom: ^26.0.0
  npm-run-all2: ^7.0.2
  prettier: ^3.5.2
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.1
  sass-embedded: ^1.85.0
  typescript: ~5.7.2
  vite: ^6.1.0
  vite-plugin-vue-devtools: ^7.7.2
  vitest: ^3.0.5
  vue: ^3.3.4
  vue-eslint-parser: ^9.4.3
  vue-router: ^4.2.4
  vue-tsc: ^2.2.2
