packages:
  - packages/app/*
  - packages/features/top/*
  - packages/features/note/*
  - packages/features/user/*
  - packages/features/shared/*
  - packages/shared/*
  - packages/di
catalog:
  "@tsconfig/node22": ^22.0.0
  "@types/jsdom": ^21.1.7
  "@types/node": ^22.13.4
  "@vitejs/plugin-vue": ^5.2.1
  "@vue/test-utils": ^2.4.6
  "@vue/tsconfig": ^0.7.0
  inversify: ^6.2.2
  jsdom: ^26.0.0
  npm-run-all2: ^7.0.2
  reflect-metadata: ^0.1.13
  rxjs: ^7.8.2
  sass-embedded: ^1.85.0
  typescript: ~5.7.3
  vite: ^6.1.0
  vite-plugin-vue-devtools: ^7.7.2
  vitest: ^3.0.5
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.2
